jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /api-tienda-adn
      session:
         timeout: 21600s

spring:
   h2:
      enabled: true
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:~/tiendaAdn
      username: root
      password: root
      hikari:
         poolName: pool

